UMLEditor
mucsci-students/2020fa-420-CovidSurvivors pull request #22
Opened 2020-09-07 23:43 UTC by 16aburnett

2020-09-08 00:00 UTC, adjusic reviewed
Looks good!

2020-09-08 00:12 UTC, 16aburnett commented on code/UMLEditor.py
> +# from UMLModel import UMLModel
Remember to un-comment this

2020-09-08 02:05 UTC, carlishires reviewed
I am getting this error when I try to run the UMLEditor.
<img width="382" alt="umlEditorError" src="https://user-images.githubusercontent.com/48737467/92425780-3b254080-f156-11ea-9d17-ca8e23b74415.PNG">

2020-09-08 02:10 UTC, carlishires commented
I also got this error when I uncommented line 5.
<img width="442" alt="umleditorerror2" src="https://user-images.githubusercontent.com/48737467/92426050-ed5d0800-f156-11ea-8ff2-12f62edb495f.PNG">

2020-09-08 03:47 UTC, 16aburnett commented
> I also got this error when I uncommented line 5.
> <img alt="umleditorerror2" width="442" src="https://user-images.githubusercontent.com/48737467/92426050-ed5d0800-f156-11ea-8ff2-12f62edb495f.PNG">

This branch only has the UMLEditor file and depends on the UMLModel class, so it is not expected to work pre-merge. If you comment out anything that mentions UMLModel then it should work fine. I should have left them commented out.

2020-09-08 21:45 UTC, carlishires requested changes
I found that "To be implemented" is printed out no matter what I enter into the command line.  I suggest that this should only be the case if the user inputs a valid command.
<img width="149" alt="umlEditorKeysmash" src="https://user-images.githubusercontent.com/48737467/92530713-e4be0d80-f1fa-11ea-861f-f222e7e4d3ac.PNG">

2020-09-09 00:42 UTC, 16aburnett commented
> I found that "To be implemented" is printed out no matter what I enter into the command line. I suggest that this should only be the case if the user inputs a valid command.
> <img alt="umlEditorKeysmash" width="149" src="https://user-images.githubusercontent.com/48737467/92530713-e4be0d80-f1fa-11ea-861f-f222e7e4d3ac.PNG">

I believe david created a task where he planned on validating commands so i made it his job to implement validating commands in the execute function. 

(I know, this whole project has been so disorganized, we really should have assigned tasks better, but we should be able to move forward.)

2020-09-09 01:59 UTC, DavitPetro approved these changes
Looks good to start implementing code!

2020-09-09 02:05 UTC, merged