Help message
mucsci-students/2020fa-420-CovidSurvivors pull request #27
Opened 2020-09-09 18:48 UTC by 16aburnett

2020-09-09 19:04 UTC, 16aburnett commented on code/UMLEditor.py
> +
As a separate task, we can go through and add in all the commands, usage statements, and descriptions. This was just a sample to test that the function works

2020-09-09 19:34 UTC, 16aburnett commented
Should we move the command usages and descriptions into its own file? It really clutters the UMLEditor file

2020-09-10 00:38 UTC, carlishires requested changes
Typing "help" in the command line while UMLEditor does only outputs "To be implemented".

2020-09-10 01:33 UTC, 16aburnett commented
> Typing "help" in the command line while UMLEditor does only outputs "To be implemented".

The "To be implemented" comes from the execute function which is what David and Adisa were working on.

2020-09-10 04:43 UTC, carlishires commented
> > Typing "help" in the command line while UMLEditor does only outputs "To be implemented".
> 
> The "To be implemented" comes from the execute function which is what David and Adisa were working on.

Alright, thanks for telling me.

2020-09-10 04:44 UTC, carlishires approved these changes
print_help_message appears to be in working order

2020-09-10 04:45 UTC, merged